#!/bin/bash
# Build script for BPI-R4 kernel user programs

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Create output directory
mkdir -p bin

# List of programs to build
PROGRAMS="shell"

# Build each program
for prog in $PROGRAMS; do
    echo "Building $prog..."

    # Build with cargo (from the program's directory)
    (cd "$prog" && cargo build --release)

    # Copy ELF to bin directory
    cp "target/aarch64-unknown-none/release/$prog" "bin/$prog.elf"

    # Convert to raw binary
    rust-objcopy -O binary \
        "target/aarch64-unknown-none/release/$prog" \
        "bin/$prog.bin"

    # Show size info
    echo "  ELF: $(ls -lh "bin/$prog.elf" | awk '{print $5}')"
    echo "  BIN: $(ls -lh "bin/$prog.bin" | awk '{print $5}')"

    # Generate Rust include file for embedding in kernel
    PROG_UPPER=$(echo "$prog" | tr '[:lower:]' '[:upper:]')
    echo "  Generating bin/${prog}_elf.rs..."
    {
        echo "//! Auto-generated ELF binary for $prog"
        echo "//! Generated by user/build.sh"
        echo ""
        echo "#[rustfmt::skip]"
        echo "pub static ${PROG_UPPER}_ELF: &[u8] = &["
        xxd -i < "bin/$prog.elf" | sed 's/^/    /'
        echo "];"
    } > "bin/${prog}_elf.rs"
done

echo ""
echo "Build complete!"
echo ""
echo "Files generated in: $SCRIPT_DIR/bin/"
echo "  - *.elf   : ELF executables"
echo "  - *.bin   : Raw binaries"
echo "  - *_elf.rs: Rust files for embedding in kernel"
echo ""
echo "To embed in kernel, copy the *_elf.rs content to src/elf.rs"
