#!/bin/bash
# Build script for BPI-R4 kernel user programs

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Create output directory
mkdir -p bin

# List of programs to build (name:path pairs, path defaults to name if not specified)
# Note: usbd replaces usbtest as the main USB daemon
# msc: Mass Storage Class driver (communicates with usbd via IPC)
PROGRAMS="shell gpio usbd:driver/usbd msc:driver/msc fatfs:driver/fatfs"

# Build each program
for entry in $PROGRAMS; do
    # Split name:path, default path to name
    prog="${entry%%:*}"
    path="${entry#*:}"
    if [ "$path" = "$prog" ]; then
        path="$prog"
    fi

    echo "Building $prog (from $path)..."

    # Build with cargo (from the program's directory)
    # Override rustflags to prevent kernel's linker script from being used
    (cd "$path" && RUSTFLAGS="-C link-arg=-Tuser.ld -C link-arg=--gc-sections -C link-arg=-n" cargo build --release)

    # Copy ELF to bin directory
    cp "target/aarch64-unknown-none/release/$prog" "bin/$prog.elf"

    # Convert to raw binary
    rust-objcopy -O binary \
        "target/aarch64-unknown-none/release/$prog" \
        "bin/$prog.bin"

    # Show size info
    echo "  ELF: $(ls -lh "bin/$prog.elf" | awk '{print $5}')"
    echo "  BIN: $(ls -lh "bin/$prog.bin" | awk '{print $5}')"

    # Generate Rust include file for embedding in kernel
    PROG_UPPER=$(echo "$prog" | tr '[:lower:]' '[:upper:]')
    echo "  Generating bin/${prog}_elf.rs..."
    {
        echo "//! Auto-generated ELF binary for $prog"
        echo "//! Generated by user/build.sh"
        echo ""
        echo "#[rustfmt::skip]"
        echo "pub static ${PROG_UPPER}_ELF: &[u8] = &["
        xxd -i < "bin/$prog.elf" | sed 's/^/    /'
        echo "];"
    } > "bin/${prog}_elf.rs"
done

echo ""
echo "Build complete!"
echo ""
echo "Files generated in: $SCRIPT_DIR/bin/"
echo "  - *.elf   : ELF executables"
echo "  - *.bin   : Raw binaries"
echo "  - *_elf.rs: Rust files for embedding in kernel"
echo ""
echo "To embed in kernel, copy the *_elf.rs content to src/elf.rs"
